# Generated by Django 5.1 on 2024-08-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titanicpassenger',
            name='age',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
